[interpark]
title = "인터파크 티켓"
url = "http://ticket.interpark.com/Webzine/Paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=0&stext=&KindOfGoods=&Genre=&sort="
entrySelector = "tbody > tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td[class='date']"
waitUntil = "networkidle"

[interpark_m]
title = "인터파크 티켓 모바일"
url = "http://mticket.interpark.com/Notice/"
entrySelector = "div[class='list'] div.item"
titleSelector = "p[class='label']"
linkSelector = "a"
contentSelector = "dl[class='ticketOpen'] > dd"
imageSelector = "span img"
waitUntil = "networkidle"