[default]
timeout = 180

[ticket]
title = "인터파크 티켓"
url = "http://ticket.interpark.com/Webzine/Paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=0&stext=&KindOfGoods=&Genre=&sort="
entrySelector = "tbody > tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td[class='date']"
waitForSelector = "td[class='subject']"
onFail = "stale"

[ticket_m]
title = "인터파크 티켓 모바일"
url = "http://mticket.interpark.com/Notice/"
entrySelector = "div[class='list'] div.item"
titleSelector = "p[class='label']"
linkSelector = "a"
contentSelector = "dl[class='ticketOpen'] > dd"
imageSelector = "span img"
waitForSelector = "td[class='subject']"
onFail = "stale"

[ticket_online]
title = "인터파크 티켓 ─ 온라인"
url = "http://ticket.interpark.com/webzine/paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=1&KindOfGoods=TICKET&Genre=&sort=WriteDate&stext=%BF%C2%B6%F3%C0%CE"
entrySelector = "tbody tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td.date"
waitForSelector = "td[class='subject']"
onFail = "stale"

[ticket_musical]
title = "인터파크 티켓 ─ 뮤지컬"
url = "http://ticket.interpark.com/webzine/paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=1&KindOfGoods=TICKET&Genre=&sort=WriteDate&stext=%B9%C2%C1%F6%C4%C3"
entrySelector = "tbody tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td.date"
waitForSelector = "td[class='subject']"
onFail = "stale"

[ticket_fanclub]
title = "인터파크 티켓 ─ 팬클럽"
url = "http://ticket.interpark.com/webzine/paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=1&KindOfGoods=TICKET&Genre=&sort=WriteDate&stext=%C6%D2%C5%AC%B7%B4"
entrySelector = "tbody tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td.date"
waitForSelector = "td[class='subject']"
onFail = "stale"

[ticket_fanmeeting]
title = "인터파크 티켓 ─ 팬미팅"
url = "http://ticket.interpark.com/webzine/paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=1&KindOfGoods=TICKET&Genre=&sort=WriteDate&stext=%C6%D2%B9%CC%C6%C3"
entrySelector = "tbody tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td.date"
waitForSelector = "td[class='subject']"
onFail = "stale"

[ticket_festival]
title = "인터파크 티켓 ─ 페스티벌"
url = "http://ticket.interpark.com/webzine/paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=1&KindOfGoods=TICKET&Genre=&sort=WriteDate&stext=%C6%E4%BD%BA%C6%BC%B9%FA"
entrySelector = "tbody tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td.date"
waitForSelector = "td[class='subject']"
onFail = "stale"
