name: indefinite commits

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
        with:
          time_elapsed: 3
